### PR TITLE
Use std::isnan and std::isinf.

### PR DESCRIPTION
**Pull request by cfcohen**
I'm not certain that this is correct, but it solved my build problem, and it looks reasonable.

### CODE REVIEW

**Comment by cignoni** [comment]
Hi, on what platform you get problems?

**Comment by cfcohen** [comment]
Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Without the change, the compilation errors are:

```
/home/cory/Source/VCGLib/vcg/math/base.h:199:51: error: ‘isnan’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
 template<class T> int IsNAN(T t) {    return isnan(t) || isinf(t); }
                                                   ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:85,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/qgl.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/QGLWidget:1,
                 from vcgmesh.cpp:7:
/usr/include/c++/5/cmath:641:5: note: ‘template<class _Tp> constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, bool>::__type std::isnan(_Tp)’ declared here, later in the translation unit
     isnan(_Tp __x)
     ^
In file included from /home/cory/Source/VCGLib/vcg/space/deprecated_point3.h:99:0,
                 from /home/cory/Source/VCGLib/vcg/space/point3.h:25,
                 from /home/cory/Source/VCGLib/vcg/complex/used_types.h:26,
                 from /home/cory/Source/VCGLib/vcg/complex/complex.h:42,
                 from vcgmesh.cpp:13:
/home/cory/Source/VCGLib/vcg/math/base.h:199:63: error: ‘isinf’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
 template<class T> int IsNAN(T t) {    return isnan(t) || isinf(t); }
                                                               ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:85,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/qgl.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/QGLWidget:1,
                 from vcgmesh.cpp:7:
/usr/include/c++/5/cmath:621:5: note: ‘template<class _Tp> constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, bool>::__type std::isinf(_Tp)’ declared here, later in the translation unit
     isinf(_Tp __x)
```

**Comment by cignoni** [comment]
Hi, I have just installed a fresh ubuntu and I have found your patch correct. 

I will merge your pull request as soon as you have signed the CLA available on 
https://github.com/cnr-isti-vclab/vcglib/blob/devel/docs/ContributorLicenseAgreement.pdf

Thanks for your help!

**Comment by cfcohen** [comment]
The PDF does not have fillable forms, and I'm not going to print it, fill it out, and scan it in.  I license this commit in the public domain, and if you prefer, I agree to the following terms for this commit:

The following terms are used throughout this agreement:
You - the person or legal entity including its affiliates asked to accept this agreement.
An affiliate is any entity that controls or is controlled by the legal entity, or is under
common control with it.
VCLab - the legal representative of the Visual Computing Lab of the ISTI-CNR
(Istituto di Scienza e Tecnologie dell’Informazione “A. Faedo” an Institute of CNR, the
National Research Council of Italy).
Project - is an umbrella term that refers to any and all the open source projects
managed by the VCLab, including, but not limited to, MeshLab and the vcglib.
Contribution - any type of work that is submitted to a Project, including any
modifications or additions to existing work.
Submitted - conveyed to a Project via a pull request, commit, issue, or any form of
electronic, written, or verbal communication with GitHub, contributors or maintainers.
1.	Grant	of	Copyright	License.
Subject to the terms and conditions of this agreement, You grant to the Projects’ maintainers
and to VCLab a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable
copyright license to reproduce, prepare derivative works of, publicly display, publicly perform,
sublicense, and distribute Your contributions and such derivative works. Except for this
license, You reserve all rights, title, and interest in your contributions.
2.	Grant	of	Patent	License.
Subject to the terms and conditions of this agreement, You grant to the Projects’ maintainers
and to VCLab a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable
(except as stated in this section) patent license to make, have made, use, offer to sell, sell,
import, and otherwise transfer your contributions, where such license applies only to those
patent claims licensable by you that are necessarily infringed by your contribution or by
combination of your contribution with the project to which this contribution was submitted.
If any entity institutes patent litigation - including cross-claim or counterclaim in a lawsuit -
against You alleging that your contribution or any project it was submitted to constitutes or is
responsible for direct or contributory patent infringement, then any patent licenses granted
to that entity under this agreement shall terminate as of the date such litigation is filed.
3.	Source	of	Contribution.
Your contribution is either your original creation, based upon previous work that, to the best
of your knowledge, is covered under an appropriate open source license and you have the
right under that license to submit that work with modifications, whether created in whole or
in part by you, or you have clearly identified the source of the contribution and any license or
other restriction (like related patents, trademarks, and license agreements) of which you are
personally aware.

If that's not good enough.  You can always troubleshoot the problem and develop you own patch.   I think it's pretty obvious what the require change would be...

**Pull request closed without merging**
