### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by dima74**

### CODE REVIEW

**Comment by alemuntoni** [comment]
Hi @dima74, thanks for this PR!
To accept this (and others) PR, I need that every contributor first signs this [CLA](https://github.com/cnr-isti-vclab/vcglib/blob/master/docs/ContributorLicenseAgreement.pdf). Sorry for the bureaucracy! 
Please send the document signed to me (muntoni.alessandro@gmail.com) and Paolo (paolo.cignoni@isti.cnr.it) and then I'll merge the pull request :)

**Comment by dima74** [comment]
@alemuntoni Hi! I just sent you CLA. But instead of this PR please merge #69

**Comment by alemuntoni** [comment]
Cool, thanks! I'll wait the CLA signed by @rpavlik, then I'll merge #69 and I'll close this :)

**Comment by alemuntoni** [comment]
Fixed in [this](https://github.com/cnr-isti-vclab/vcglib/commit/f7871eed2d54bee704b9f66dc538c921602323cb) commit.

**Pull request closed without merging**
